version: '3'

services:
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    restart: on-failure
    ports:
      - 3001:3001
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - ./envs:/home/node/app/envs
    extra_hosts:
      - "host.docker.internal:host-sensor"
