apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Deployment.yaml
- Service.yaml

images:
- name: app-sensor
  newName: manscalh/app-sensor
  newTag: 73bc449b6f12487ec11d04a8c095c49315c3692f
