apiVersion: v1
kind: Service
metadata:
  name: app-sensor-service
spec:
  type: LoadBalancer
  selector:
    app: app-sensor
  ports:
  - port: 3001        #SERVICE URL
    targetPort: 3001  #CONTAINER
    # nodePort: 30001   #CLUSTER